development:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "solr") %>
    port: <%= ENV.fetch("SOLR_PORT", 8983) %>
    path: /solr/solr_development
    log_level: INFO
    read_timeout: 2
    open_timeout: 1

test:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port: <%= ENV.fetch("SOLR_PORT", 8982) %>
    path: /solr/solr_test
    log_level: WARNING
    read_timeout: 2
    open_timeout: 1

production:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port: <%= ENV.fetch("SOLR_PORT", 8983) %>
    path: <%= ENV.fetch("SOLR_PATH", "/solr/production") %>
    log_level: WARNING
    read_timeout: 5
    open_timeout: 2